### ISSUE TITLE
Use module in renderer without node integration 

### ISSUE THREAD

**Issue by DRBragg** [vincelwt/electron-nucleus#4]
If I include nucleus in my renderer the app only shows a white screen and I see the following in my console:
![Screen Shot 2019-08-16 at 12 15 37 PM](https://user-images.githubusercontent.com/26798548/63182152-d6b1b380-c01f-11e9-8e4e-c196bffb33e9.png)

If I only include nucleus in my main process and us the `isMainProcess` flag the app will render but then I don't have access to nucleus to actually track anything.  I've fix every issue/error/warning that popped up but still can get it to work.  

Any idea of where I should look next?

**Comment by vincelwt** [comment]
Did you disable the `nodeIntegration` in the renderer process? This may be the cause.

One way to bypass the issue is by using Nucleus only in the main process and communicate events via IPC between processes. 

However to make sure errors in the renderer are caught you would have to add the listener manually:

```
window.onError = function(msg, url, line, col, error) {

   // Send the error via IPC to the main process
   ipc.send('windowError',  JSON.stringify(error))
    
}
```

and in the main process:

```
ipc.on('windowError', function (event, arg) {
    const error = JSON.parse(arg)
    Nucleus.trackError('windowError', error)
})
```

**Comment by vincelwt** [comment]
I think the module should if possible support your case of not having access to the Node modules. I'll make some tests to see if it's possible to keep all features, how to detect that case and use the built-in browser's Websocket agent.

**Comment by vincelwt** [comment]
The new [nucleus-nodejs](/nucleus-sh/nucleus-nodejs) module is now able to function in a browser context without access to Node (although that restricts some features) and uses when possible the browser native Websocket implementation. 

(The methods are a bit different so just switching the old module for the new one won't work)
